name: CMake Git Version Tracking

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: get cmake and ninja
      uses: lukka/get-cmake@latest
    - name: run tests
      run: |
        git config --global user.email "ci@example.com"
        git config --global user.name "CI"
        ./tests/run_all.sh
        ./tests/run_examples.sh
